- name: Setup target
  hosts: all
  vars:
    vcvars_path: "{{ ansible_env['ProgramFiles'] }}\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
    dest_path: "C:\\Users\\Public"
    wdk_include_km_path: "C:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17763.0\\km"
    wdk_lib_path: "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.17763.0\\km\\x64"
    ntoskrnllib_path: "C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.17763.0\\km\\x64\\ntoskrnl.lib"
  tasks:
    - name: Upload binaries1
      win_copy:
        src: "/home/fuzzer/kAFL/kafl/examples/windows_x86_64/bin/userspace/inject.exe"
        dest: "{{ dest_path }}"
    - name: Upload binaries2
      win_copy:
        src: "/home/fuzzer/kAFL/kafl/examples/windows_x86_64/bin/userspace/hightosys.exe"
        dest: "{{ dest_path }}"
    - name: Upload binaries3
      win_copy:
        src: "/home/fuzzer/kAFL/kafl/examples/windows_x86_64/bin/userspace/kafl_sysmain.dll"
        dest: "{{ dest_path }}"

    - name: Setup userspace harness to run at user login with elevated privileges
      win_service:
        name: vuln
        path: "C:\\Users\\Public\\hightosys.exe"
        start_mode: auto