- name: Deploy
  hosts: default
  vars:
    vsix_installer: "{{ ansible_env['ProgramFiles'] }}\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\VSIXInstaller.exe"
    wdk_vsix_dir: "{{ ansible_env['ProgramFiles(x86)'] }}\\Windows Kits\\10\\Vsix\\VS2022\\10.0.22621.0"
  tasks:
    # This should be set before running the win_inet_proxy module
    - name: Configure IE proxy settings to apply to all users
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
        name: ProxySettingsPerUser
        data: 0
        type: dword
        state: present
      when: ansible_proxy | length > 0

    - name: Configure IE proxy settings
      win_inet_proxy:
        auto_detect: no
        proxy: "{{ ansible_proxy }}"
      when: ansible_proxy | length > 0

    # This should be done after setting the IE proxy with win_inet_proxy
    - name: Import IE proxy configuration to WinHTTP
      win_http_proxy:
        source: ie
      when: ansible_proxy | length > 0

    - name: Ensure Chocolatey installed from internal repo
      win_chocolatey:
        name: chocolatey
        proxy_url: "{{ ansible_proxy }}"

    - name: Set chocolatey proxy
      win_chocolatey_config:
        name: proxy
        state: present
        value: "{{ ansible_proxy }}"
      when: ansible_proxy | length > 0

    - name: Disable uncessary services
      win_service:
        name: "{{ item }}"
        state: stopped
        start_mode: disabled
      with_items:
        - WSearch
        - Spooler

    - name: Disable OneDrive
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\OneDrive
        name: DisableFileSyncNGSC
        data: 1
        type: dword
        state: present

    - name: Disable Cortana
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\Windows Search
        name: AllowCortana
        data: 0
        type: dword
        state: present

    - name: Disable Defender
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Microsoft Defender
        name: DisableAntiSpyware
        data: 1
        type: dword
        state: present

    # Windows Update Tasks
    - name: Enable Windows Update Service
      win_service:
        name: wuauserv
        start_mode: auto
        state: started

    - name: Enable Background Intelligent Transfer Service
      win_service:
        name: bits
        start_mode: auto
        state: started

    - name: Enable Windows Update Orchestrator Service
      win_service:
        name: UsoSvc
        start_mode: auto
        state: started

    - name: Install NuGet Provider for PowerShell
      win_shell: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
      ignore_errors: yes

    - name: Install Windows Update PowerShell Module
      win_shell: Install-Module -Name PSWindowsUpdate -Force -AllowClobber
      ignore_errors: yes

    - name: Configure Automatic Updates
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update
        name: AUOptions
        data: 4  # 4 = Automatically download and install
        type: dword
        state: present

    - name: Install All Available Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - DefinitionUpdates
        state: installed
        reboot: yes
        reboot_timeout: 3600
      register: windows_update_result

    - name: Enable Testsigning
      win_command: Bcdedit.exe -set TESTSIGNING ON

    - name: Disable password expiration
      win_command: net user Vagrant /expires:never
